### ISSUE TITLE
Remove unnecessary 3x failure that has been there since the dawn of time?

### ISSUE THREAD

**Issue by rclai** [meteor/meteor-feature-requests#352]
Is there any reason why you guys are trying 3 times to build code that is already broken?

Example
```js
// server/main.js

tarnations
```

Output
```
=> Started proxy.                             
W20190327-10:05:05.218(-4)? (STDERR) /Users/richardlai/.meteor/packages/meteor-tool/.1.8.1-beta.16.1jn3kcq.b1cd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190327-10:05:05.250(-4)? (STDERR)                     throw(ex);
W20190327-10:05:05.250(-4)? (STDERR)                     ^
W20190327-10:05:05.250(-4)? (STDERR) 
W20190327-10:05:05.250(-4)? (STDERR) ReferenceError: tarnations is not defined
W20190327-10:05:05.251(-4)? (STDERR)     at main.js (src/server/main.js:5:1)
W20190327-10:05:05.251(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190327-10:05:05.251(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190327-10:05:05.251(-4)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190327-10:05:05.251(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/app/app.js:1046:15
W20190327-10:05:05.251(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:411:36
W20190327-10:05:05.251(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20190327-10:05:05.251(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:220:19
W20190327-10:05:05.252(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:471:5
W20190327-10:05:05.252(-4)? (STDERR)     at Function.run (/Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/profile.js:510:12)
W20190327-10:05:05.254(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
W20190327-10:05:06.646(-4)? (STDERR) /Users/richardlai/.meteor/packages/meteor-tool/.1.8.1-beta.16.1jn3kcq.b1cd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190327-10:05:06.646(-4)? (STDERR)                     throw(ex);
W20190327-10:05:06.646(-4)? (STDERR)                     ^
W20190327-10:05:06.647(-4)? (STDERR) 
W20190327-10:05:06.647(-4)? (STDERR) ReferenceError: tarnations is not defined
W20190327-10:05:06.647(-4)? (STDERR)     at main.js (src/server/main.js:5:1)
W20190327-10:05:06.647(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190327-10:05:06.647(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190327-10:05:06.647(-4)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190327-10:05:06.648(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/app/app.js:1046:15
W20190327-10:05:06.648(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:411:36
W20190327-10:05:06.648(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20190327-10:05:06.648(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:220:19
W20190327-10:05:06.648(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:471:5
W20190327-10:05:06.649(-4)? (STDERR)     at Function.run (/Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/profile.js:510:12)
W20190327-10:05:06.649(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
W20190327-10:05:08.300(-4)? (STDERR) /Users/richardlai/.meteor/packages/meteor-tool/.1.8.1-beta.16.1jn3kcq.b1cd++os.osx.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20190327-10:05:08.300(-4)? (STDERR)                     throw(ex);
W20190327-10:05:08.301(-4)? (STDERR)                     ^
W20190327-10:05:08.301(-4)? (STDERR) 
W20190327-10:05:08.301(-4)? (STDERR) ReferenceError: tarnations is not defined
W20190327-10:05:08.301(-4)? (STDERR)     at main.js (src/server/main.js:5:1)
W20190327-10:05:08.301(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)
W20190327-10:05:08.301(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)
W20190327-10:05:08.302(-4)? (STDERR)     at require (packages/modules-runtime.js:258:21)
W20190327-10:05:08.302(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/app/app.js:1046:15
W20190327-10:05:08.302(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:411:36
W20190327-10:05:08.302(-4)? (STDERR)     at Array.forEach (<anonymous>)
W20190327-10:05:08.302(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:220:19
W20190327-10:05:08.302(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:471:5
W20190327-10:05:08.303(-4)? (STDERR)     at Function.run (/Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/profile.js:510:12)
W20190327-10:05:08.303(-4)? (STDERR)     at /Users/richardlai/Profab/vue-meteor/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by klaussner** [comment]
This feature will be removed in Meteor 1.9.0. 🙂 See https://github.com/meteor/meteor/pull/10345.

**Comment by rclai** [comment]
Yay!
