### ISSUE TITLE
Path aliases for modules

### ISSUE THREAD

**Issue by joncursi** [meteor/meteor-feature-requests#60]
Migrated from: meteor/meteor#5869

I'm having a really hard time porting my React Native components over for usage on the web inside Meteor via [react-native-web](https://github.com/necolas/react-native-web). React Native Web [recommends in their setup guide](https://github.com/necolas/react-native-web/blob/master/docs/guides/getting-started.md#webpack-and-babel) creating an alias on node_modules to map `react-native` imports to `react-native-web`, but this is not possible on web. 

Instead of a simple configuration, you are forced to use [sloppy solutions like this](https://github.com/meteor/meteor/issues/8768#issuecomment-306985899). This is bad for two reasons:

1) It's ugly code, and Flow and ESLint can't interpret it
2) Because you have to manually declare the module to import from, you lose out on the ability to use any 3rd party modules that have a specific import baked into their source code, such as [`react-native-image-progress`](https://github.com/oblador/react-native-image-progress/blob/master/index.js#L6). Which means you end up asking for [bad feature requests](https://github.com/oblador/react-native-image-progress/issues/37) on these third party modules to work around Meteor's limitations.

**Comment by benjamn** [comment]
Meteor's runtime module system supports aliases:
```js
meteorInstall({
  node_modules: {
    "react-native": "react-native-web"
  }
});
```
However, this is only a runtime remapping, so you need to
1. make sure `react-native-web` is getting bundled due to a `require("react-native-web")` import somewhere else in your code, and
2. make sure that `/node_modules/react-native` is not included in the bundle, because it will take precedence over the alias (see [this comment](https://github.com/meteor/meteor/issues/8768#issuecomment-307124476) for an idea).

**Comment by mitar** [comment]
For same idea for Atmosphere packages, see #47.

**Comment by joncursi** [comment]
@benjamn Hmm... would you be able to provide a slightly deeper code example, or is this `meteorInstall` configuration documented somewhere where I can learn more about it? I tried inserting the code snippet you gave in both Meteor client and server startup code but my app keeps complaining with `Uncaught Error: Cannot find module 'react-native'`.

To give some more context on how I have my system setup: my setup isn't a mono-repo, it's actually three different modules / projects that are independently versioned:

The "core" project: houses all universal JavaScript code, and exports a common set of components. This is a private npm module:
```
// project-core/lib/components/View.js
/* @flow */

import Platform from '../Platform';

const rnId = 'react-native';
const {
  View,
// $FlowFixMe
} = Platform.OS === 'web' ? require('react-native-web') : require(rnId); // eslint-disable-line

export default View;
```

The "native" project: houses all iOS and Android specific code; depends on core project to build out screens with a common set of JS and components. The genesis of this repo was initialized using `react-native init`:
```js
// project-native/imports/ui/SomeScreen.js
import View from 'project-core/lib/components/View'; // React Native manages this repository's imports

const Component = () => (
  <View>
    { ... }
  </View>
);
```

The "web" project: houses all iOS and Android specific code; depends on core project to build out screens with a common set of JS and components. The genesis of this repo was initialized using `meteor create`:
```js
// project-web/imports/ui/SomeScreen.js
import View from 'project-core/lib/components/View'; // Meteor manages this repository's imports

const Component = () => (
  <View>
    { ... }
  </View>
);
```

I'm trying to figure out a better way to export universal components from `project-core`. After playing around with this for a few days, I have come to the conclusion that I have __two needs__ here:

A) Need: the Meteor `project-web` and the ReactNative `project-native` should be able to import / require the same component. (As you can see [here](https://github.com/meteor/meteor/issues/8768#issuecomment-306992030), I am having a very hard time achieving this as the Meteor build system and react-native's build system handle the build process differently.)

B) Want: Rather than using `if` / `else` checks all over the place in the core project to try and figure out which client project is consuming the code (and then import from the "appropriate" npm module: `react-native` or `react-native-web`), I would prefer to have all of my core code simply import from the `react-native` namespace. This has two benefits:

1) This will work out of the box in React Native, and if Meteor does support aliasing (though I haven't been able to get it to work myself), it would run in Meteor as well with a small amount of configuration in `project-web`. Because I am now importing from a single source, I don't need to have the core project depend on `react-native-web`, and I can delete the ternary expressions, and Flow and ESLint will be way happier.

2) There are tons of 3rd party modules that are built around the react-native component primitives, such as [react-native-image-progress](https://github.com/oblador/react-native-image-progress/blob/master/index.js#L6-L12). Because both client projects would know how to handle imports that come from the `react-native` namespace, either project can use any 3rd party module that depends only on this same set of component primitives without [requiring any additional configuration / burden](https://github.com/oblador/react-native-image-progress/issues/37) on these 3rd party modules to explicitly support web clients. Essentially, my web app would get access to these 3rd part modules "for free".

----

Would you be able to help me understand how I can modify the above setup to achieve these two needs?

**Comment by benjamn** [comment]
That `meteorInstall` code has to run before you import `react-native` for the first time. You might want to look at your code in DevTools without source maps to make sure things are happening in the order you expect.

**Comment by zimme** [comment]
If this technically is possible in Meteor, maybe this should be a FR for documentation?

**Comment by joncursi** [comment]
+1 for documentation or some sort of concrete example. Maybe a simple repo? I'm still having trouble with this. I've tried removing all client and server code and just writing this in a brand new Meteor app:

```
// client/main.js

meteorInstall({
  node_modules: {
    "react-native": "react-native-web"
  }
});

const TextComponentOne = require('react-native-web').Text;

const TextComponentTwo = require('react-native').Text; // error happens here
```

and it errors out with

```
Uncaught Error: Cannot find module 'Text'
```

<img width="469" alt="screen shot 2017-06-12 at 3 08 08 am" src="https://user-images.githubusercontent.com/4974609/27022528-65b0df06-4f1c-11e7-8f98-5be0813bf186.png">

Here is my entire `app.js` file that Meteor generates (it looks like `meteorInstall` comes first as you described?):

```js
var require = meteorInstall({"client":{"template.main.js":function(){

///////////////////////////////////////////////////////////////////////
//                                                                   //
// client/template.main.js                                           //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
Meteor.startup(function() {                                          // 1
  var attrs = {"bgcolor":"#fafafa"};                                 // 2
  for (var prop in attrs) {                                          // 3
    document.body.setAttribute(prop, attrs[prop]);                   // 4
  }                                                                  // 5
});                                                                  // 6
                                                                     // 7
///////////////////////////////////////////////////////////////////////

},"main.js":function(require){

///////////////////////////////////////////////////////////////////////
//                                                                   //
// client/main.js                                                    //
//                                                                   //
///////////////////////////////////////////////////////////////////////
                                                                     //
"use strict";                                                        //
                                                                     //
meteorInstall({                                                      // 5
  node_modules: {                                                    //
    "react-native": "react-native-web"                               //
  }                                                                  // 3
});                                                                  // 4
                                                                     //
var asd = require('react-native-web').Text;                          // 11
                                                                     //
var def = require('react-native').Text;                              //
///////////////////////////////////////////////////////////////////////

}}},{
  "extensions": [
    ".js",
    ".json",
    ".html",
    ".css",
    ".graphql",
    ".jsx"
  ]
});
require("./client/template.main.js");
require("./client/main.js");
```

**Comment by artpolikarpov** [comment]
@joncursi try to add `import 'react-native-web';` just before your `meteorInstall` call.

**Comment by Falieson** [comment]
webpack has had import alias resolving for a long time now... relative imports can't possibly be a good idea for a maintainable application!

**Comment by joncursi** [comment]
@benjamn does `meteorInstall` work the same on the Meteor server?

Without SSR I finally got this to work on the client by inspecting the `app.js` and making sure `meteorInstall` came first. But now that I'm trying to use SSR via `server-render`, the Meteor server is complaining now about the same stuff:

```
Error: Cannot find module 'react-native'
W20170819-18:48:36.638(-4)? (STDERR)     at Function.Module._resolveFilename (module.js:485:15)
W20170819-18:48:36.638(-4)? (STDERR)     at Function.Module._load (module.js:437:25)
W20170819-18:48:36.638(-4)? (STDERR)     at Module.require (module.js:513:17)
W20170819-18:48:36.638(-4)? (STDERR)     at require (internal/module.js:11:18)
W20170819-18:48:36.639(-4)? (STDERR)     at Object.<anonymous> (/Users/joncursi/Sites/joncursi/redbird-web/node_modules/react-native-vector-icons/dist/lib/react-native.js:1:75)
W20170819-18:48:36.639(-4)? (STDERR)     at Module._compile (module.js:569:30)
W20170819-18:48:36.639(-4)? (STDERR)     at Object.Module._extensions..js (module.js:580:10)
W20170819-18:48:36.639(-4)? (STDERR)     at Module.load (module.js:503:32)
W20170819-18:48:36.639(-4)? (STDERR)     at tryModuleLoad (module.js:466:12)
W20170819-18:48:36.640(-4)? (STDERR)     at Function.Module._load (module.js:458:3)
```

The same `app.js` is working great on the client, but failing on the server. Any ideas?

**Comment by Telokis** [comment]
I don't know why but nothing changes at all when I use meteorInstall.

At the very top of `client/main.jsx` and `server/main.js`

```js
import "preact-compat";

meteorInstall({
  node_modules: {
    "react-dom": "preact-compat",
    react: "preact-compat",
  },
});```

**Comment by sakulstra** [comment]
It's also not working for me atm (but didn't do much debugging yet)

chiming in with another use/problem-case:
we run into this problem at a regular basis as from time to time `package A` has a mission critical bug and pr-merging/releasing happens to slowly. So we will release a fork for the meantime and are forced to rewrite all import statements (at least this is what we did in the past as I didn't find the current solution in the docs).
This approach get's especially annoying when `package B` relies on `package A` and both ends up in the build.

It would be cool if we had sth similar to jest moduleMapper or webpack aliases in place.

**Comment by dhamaniasad** [comment]
I tried using the `meteorInstall` method and could not get it to work. I found a `Babel` plugin that transformed imports and modified it to work with my specific use case (using preact).

You need to have `meteor-babel` installed (`meteor npm install meteor-babel`), and you'll need Babel 7. 

[Here's the plugin](https://www.npmjs.com/package/babel-plugin-meteoralias), and it'll allow you to use plugins written for React with Preact and any other use case you might have for transforming imports. 

```json
{
  "plugins": [
    ["babel-plugin-meteoralias", {
        "aliases": [
            {
                "from": "react",
                "to": "preact-compat"
            },
            {
                "from": "react-dom",
                "to": "preact-compat"
            }
        ]
    }]
  ]
}
```

**Comment by tafelito** [comment]
I was able to make this work using it like this

Option 1 - using import inside Meteor.startup

`client/main.js`
```js
import React from "react";
import "react-native-web";
import { Meteor } from "meteor/meteor";

meteorInstall({
  node_modules: {
    "react-native": "react-native-web", //
  },
});

Meteor.startup(() => {
  import { AppRegistry } from "react-native";
  import App from '../imports/ui/App';

  AppRegistry.registerComponent("App", () => App);

  AppRegistry.runApplication("App", {
    rootTag: document.getElementById("root"),
  });
});
```

Option 2 - using require

`client/main.js`
```js
import React from "react";
import "react-native-web";
import { Meteor } from "meteor/meteor";

meteorInstall({
  node_modules: {
    "react-native": "react-native-web", //
  },
});

const AppRegistry = require("react-native").AppRegistry;
const App = require("../imports/ui/App").default;

Meteor.startup(() => {
  AppRegistry.registerComponent("App", () => App);

  AppRegistry.runApplication("App", {
    rootTag: document.getElementById("root"),
  });
});
```

Is there any other way of doing it, or is it ok to do it like this?

**Comment by Batistleman** [comment]
Did you manage to solve this? I'm also still getting a warning when bundling...

**Comment by Batistleman** [comment]
@tafelito did you find a solution for this?

**Comment by dagatsoin** [comment]
I managed to use `react-native-icon` with this:

```
declare const __meteor_runtime_config__: any
declare const cordova: any
declare const meteorInstall: any

// This will make the meteor bundlers embed react-native-web
// tslint:disable-next-line: no-var-requires
import 'react-native-web'

// Then we can set an alias to replace react-native module by react-native-web
meteorInstall({
  node_modules: {
    "react-native": "react-native-web"
  }
})

import './importSpaceLift'

// tslint:disable-next-line: no-var-requires
require('/imports/startup/client')

document.addEventListener("deviceready", onDeviceReady, false)
function onDeviceReady() {
  console.log(cordova.file)
  console.log("/meteor/" + __meteor_runtime_config__.autoupdateVersionCordova)
}
```
in my tsconfig.json (remove unrevelant part)
```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "jsx": "react",
    "downlevelIteration": true,
    "module": "commonjs",
    "target": "es5",
    "noImplicitAny": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "lib": ["es2017", "dom"],
    "types": ["meteor", "jest", "node"],
    "strictNullChecks": true,
    "baseUrl": "./", 
    "paths": { 
      "react-native": ["react-native-web"],
      "~/*": [ "./imports/*" ]
    } 
  },
  "include": [
    "client/**/*",
    "imports/**/*",
    "server/**/*",
  ],
  "exclude": [
    "node_modules"
  ]
}

```

**Comment by trusktr** [comment]
The `meteorInstall` trick is too tricky. Something in https://github.com/meteor/meteor-feature-requests/issues/353 would be better, so that it applies the same across all code, without nuances.

**Comment by tafelito** [comment]
@Batistleman 
 > @tafelito did you find a solution for this?

It's working for me with either the 2 options I wrote above. The only minor "issue" with that is the warning you get, but as @benjamn said `meteorInstall` is  only a runtime remapping, so until something like webpack aliases is implemented in meteor, that's the best solution I found

**Comment by mrauhu** [comment]
# Meteor version >= 1.8.1 and NPM >= 6.9

## Example: Inferno as React in Vue

```vue
<template>
    <AutoForm :schema="ClassActionFormSchema" :onSubmit="submit"/>
</template>

<script>
  import { ReactInVue } from 'vuera';
  import { AutoForm } from 'uniforms-bootstrap4';

  import schema from './schema';

  export default {
    name: 'Form',
    data() {
      return {
        schema,
      }
    },
    methods: {
      submit(data) {
        console.log('submit() - data', data);
      }
    },
    components: {
      AutoForm: ReactInVue(AutoForm),
    }
  };
</script>
```

## Solution: NPM alias

```bash
meteor npm install --save inferno-compat react@npm:inferno-compat react-dom@npm:inferno-compat
```

**Comment by davidworkman9** [comment]
Should the `meteorInstall` trick still work? I have a slightly different use case than the ones above, I want to import a different file in the same module than the default if it's on the client. As far as I can tell calling `meteorInstall` does nothing..

This is my client main:
```
import 'type-graphql/dist/browser-shim';

meteorInstall({
    node_modules: {
        'type-graphql': 'type-graphql/dist/browser-shim',
    },
});

require('/imports/startup/client');
```

Am I missing something? Or does this just not work on newer versions of Meteor?
